<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../NetworkTools.Mod/Geometry/ConnectLaneAlignment.cs" Link="ConnectLaneAlignment.cs" />
  </ItemGroup>
</Project>
